# $schema: https://www.schemastore.org/github-action.json
name: 'Create APK Repository'
author: 'Kalle M. Aagaard <alpine@k-moeller.dk>'
description: 'Build Alpine Package'
outputs:
  repo_path:
    description: "Path with repo"
inputs:
  pkgs_path:
    description: "Path with packages"
    required: false
    default: "pkgs"
  abuild_key_name:
    description: 'Name of RSA Key to sign the package'
    required: true
  abuild_key_priv:
    description: 'Private RSA Key to sign the package'
    required: true
  abuild_key_pub:
    description: 'Public RSA Key to verify the package'
    required: true
  abuild_repo_url:
    description: 'Url for repo'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'package'  
  color: 'blue'
