version: '3'

tasks:
  default:
    cmds:
      - git add .
      - git commit -m "Update"
      - bump-my-version bump patch
      - git push --follow-tags
      - bump-my-version show scm_info.current_tag