on:
  push:
    branches:
    - main

name: Make Snapshot
jobs:
  tagger:
    name: Build Binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get tag
        id: get_tag
        run: |
          set -ex
          git fetch --tags
          version=$(git tag -l --sort=-version:refname v* | head -n 1)
          echo $version
          a=( ${version//./ } )
          ((a[2]++))
          echo "${a[0]}.${a[1]}.${a[2]}"
          echo "new_tag=${a[0]}.${a[1]}.${a[2]}" >> $GITHUB_OUTPUT
      - name: Create tag
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.get_tag.outputs.new_tag }}',
              sha: context.sha
            })